version: 2

jobs:

  build:
    docker:
      - image: rust:latest
    steps:
      - checkout

      # Load cargo target from cache if possible.
      # Multiple caches are used to increase the chance of a cache hit.
      - restore_cache:
          keys:
            - v2-cargo-cache-build-{{ arch }}-{{ .Branch }}
            - v2-cargo-cache-build-{{ arch }}

      # Install nightly & wasm
      - run:
          name: Install Rust nightly
          command: rustup update nightly && rustup default nightly
      - run:
          name: Add wasm32 target
          command: rustup target add wasm32-unknown-unknown

      # Install wasm tools
      - run:
          name: Install wasm-pack
          command: >
            curl -L https://github.com/rustwasm/wasm-pack/releases/download/v0.6.0/wasm-pack-v0.6.0-x86_64-unknown-linux-musl.tar.gz
            | tar --strip-components=1 --wildcards -xzf - "*/wasm-pack"
            && chmod +x wasm-pack
            && mv wasm-pack $CARGO_HOME/bin/

      # Show versions
      - run:
          name: Show versions
          command: rustc --version && cargo --version && wasm-pack --version

      # Build
      - run:
          name: Build
          command: wasm-pack build --release -t browser
      - persist_to_workspace:
          root: .
          paths:
            - pkg
            - selenium
            - www

      # Save cache
      - save_cache:
          key: v2-cargo-cache-build-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
      - save_cache:
          key: v2-cargo-cache-build-{{ arch }}
          paths:
            - /usr/local/cargo

  lint:
    docker:
      - image: rust:latest
    steps:
      - checkout

      # Load cargo target from cache if possible.
      # Multiple caches are used to increase the chance of a cache hit.
      - restore_cache:
          keys:
            - v2-cargo-cache-lint-{{ arch }}-{{ .Branch }}
            - v2-cargo-cache-lint-{{ arch }}

      # Install nightly
      - run:
          name: Install Rust nightly
          command: rustup update nightly-2023-11-19 && rustup default nightly-2023-11-19
      - run:
          name: Install clippy
          command: rustup component add clippy

      # Show versions
      - run:
          name: Show versions
          command: rustc --version && cargo --version && cargo clippy --version

      # Run linting checks
      - run:
          name: Run clippy
          command: cargo clean && cargo clippy --all-targets --all-features

      # Save cache
      - save_cache:
          key: v2-cargo-cache-lint-{{ arch }}-{{ .Branch }}
          paths:
            - /usr/local/cargo
      - save_cache:
          key: v2-cargo-cache-lint-{{ arch }}
          paths:
            - /usr/local/cargo

  test-unit:
    docker:
      - image: rust:latest
    steps:
      - checkout

      # Load cargo target from cache if possible.
      # Multiple caches are used to increase the chance of a cache hit.
      - restore_cache:
          keys:
            - v2-cargo-cache-unittest-{{ arch }}-{{ .Branch }}
            - v2-cargo-cache-unittest-{{ arch }}

      # Install nightly
      - run:
          name: Install Rust nightly
          command: rustup update nightly && rustup default nightly

      # Show versions
      - run:
          name: Show versions
          command: rustc --version && cargo --version

      # Run tests
      - run:
          name: Run unit tests
          command: cargo test

      # Save cache
      - save_cache:
          key: v2-cargo-cache-unittest-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
      - save_cache:
          key: v2-cargo-cache-unittest-{{ arch }}
          paths:
            - /usr/local/cargo

  test-browser:
    docker:
      - image: rust:latest
    steps:
      - checkout

      # Load cargo target from cache if possible.
      # Multiple caches are used to increase the chance of a cache hit.
      - restore_cache:
          keys:
            - v2-cargo-cache-browsertest-{{ arch }}-{{ .Branch }}
            - v2-cargo-cache-browsertest-{{ arch }}

      # Install nightly & wasm
      - run:
          name: Install Rust nightly
          command: rustup update nightly && rustup default nightly
      - run:
          name: Add wasm32 target
          command: rustup target add wasm32-unknown-unknown

      # Install wasm tools
      - run:
          name: Install wasm-pack
          command: >
            curl -L https://github.com/rustwasm/wasm-pack/releases/download/v0.6.0/wasm-pack-v0.6.0-x86_64-unknown-linux-musl.tar.gz
            | tar --strip-components=1 --wildcards -xzf - "*/wasm-pack"
            && chmod +x wasm-pack
            && mv wasm-pack $CARGO_HOME/bin/

      # Install browsers
      - run:
          name: Install latest firefox
          command: >
            apt-get update
            && apt-get install -y libgtk-3-0 libdbus-glib-1-2 libasound2 libx11-xcb1
            && wget -q -O - "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US"
            |  tar xj

      # Show versions
      - run:
          name: Show versions
          command: rustc --version && cargo --version && wasm-pack --version && firefox/firefox --version

      # Run tests
      - run:
          name: Run browser unit tests
          command: PATH=$(pwd)/firefox:$PATH wasm-pack test --headless --firefox

      # Save cache
      - save_cache:
          key: v2-cargo-cache-browsertest-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
      - save_cache:
          key: v2-cargo-cache-browsertest-{{ arch }}
          paths:
            - /usr/local/cargo

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - lint
      - test-unit
      - test-browser
